### ISSUE TITLE
Apache Directory Studio in Chocolatey out of date (M12 -> M15)

### ISSUE THREAD

**Issue by krc** [dgalbraith/chocolatey-packages#196]
Currently on Apache Directory Studio 2.0.0.1-M12 (2016), current is M15 (2020)

https://directory.apache.org/studio/downloads.html
https://directory.apache.org/studio/changelog.html
https://archive.apache.org/dist/directory/studio/2.0.0.v20200411-M15/

Choco help said contact the maintainer, this was the only way I could find easily, hope that is ok.

Looks like still uses Java 8 minimum, Java 11 and up now supported

**Comment by dgalbraith** [comment]
The package has been updated to provide the M15 version and an automatic updater has been produced which should keep it synchronised going forward.

There is an issue with the lexical ordering of versions carrying the -M?? designation that will need to be addressed - as things stand the 2.0.0-M15 release is not seen to be the latest.  Another package update will likely be required with a scheme for addressing the versions is determined.

In the interim the package can be installed directly with
`choco install apachedirectorystudio --version=2.0.0-M15 --pre`

**Comment by dgalbraith** [comment]
2.0.0-M15 now listed as the most recent version.

The issue with lexicographic ordering leading to M15 being buried has not actually been addressed but the older package versions have been unlisted from the search results.

Does this address the issue sufficiently or is there a requirement to also list prior milestone builds?

**Comment by dgalbraith** [comment]
The package i snow updating against new milestone versions correctly and the incorrectly marked versions impacting the ordering have been hidden.

The correct latest version (currently 2.0.0-M16) is listed and available so looks like this has been resolved.
