### ISSUE TITLE
Spanish keyboard doesn't allow the use of Alt Gr key to use speciall characters like '@'

### ISSUE THREAD

**Issue by zarovich** [dgalbraith/chocolatey-packages#246]
I've installed mc for windows through chocolatey, and I see that for some reason with spanish keyboard i can't use 'Alt Gr' key (or right Alt key) to use speciall characters, specially i can't type '@' for SFTP connections.

**Comment by dgalbraith** [comment]
@zarovich I don't believe that this is an issue with the package but rather the underlying software.

I have taken a look and am certainly able to replicate - if the keyboard input is ESP I don't see anything displayed on the terminal when pressed in conjunction with the Alt GR key.  I do not know enough about the underlying mc or internationalisation to be able to help further on this though.

The documentation certainly suggests that mc has I18N support so I don't see why it should not work.

Might I suggest raising an issue for @adamyg over at https://sourceforge.net/p/mcwin32/tickets?
