### ISSUE TITLE
unable to install sql reporting services 2019 with a product ID

### ISSUE THREAD

**Issue by gstorme** [dgalbraith/chocolatey-packages#272]
Hi,

It's not possible to install the choco package for SQL reporting services 2019 with a product ID.
If we specify a product ID:

`ErrorMessage:Cannot specify both Edition and PID`

Seems your script adds the "Edition:Eval" parameter by default, preventing an installation with a given PID to proceed.
Can the Edition parameter be left out when a PID is specified?

**Comment by dgalbraith** [comment]
An updated version of the [ssrs-2019 package](https://community.chocolatey.org/packages/ssrs-2019/15.0.7545.20210404)addressing this has been pushed.  The edition will now only be defaulted if a PID is not supplied.
