### ISSUE TITLE
Migrate maintenance and update the openvpn package

### ISSUE THREAD

**Issue by dgalbraith** [dgalbraith/chocolatey-packages#352]
Migrate maintenance and update the [openvpn](https://chocolatey.org/packages/openvpn) package as per the [Chocolatey community package request](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1024) from [wget/chocolatey-package-openvpn](https://github.com/wget/chocolatey-package-openvpn).

**Comment by opoplawski** [comment]
Thanks for starting this.  Any progress?

**Comment by dgalbraith** [comment]
@opoplawski package updates for the 2.5 series of OpenVPN are now available in the community repository.
