### ISSUE TITLE
misnamed nushell shims 

### ISSUE THREAD

**Issue by AeliusSaionji** [dgalbraith/chocolatey-packages#370]
oops!

![image](https://user-images.githubusercontent.com/4342746/154581331-003c6fb5-c232-477a-8f20-d993a16ba866.png)

![image](https://user-images.githubusercontent.com/4342746/154581348-8618af00-ae52-4e7f-ad80-f23e80e7d65a.png)

**Comment by dgalbraith** [comment]
nushell shims are having an additional .exe included in the shim name as the target name being used for the manual generation with `Install-BinFile` includes the `.exe` extension.  This is then appended with an additional `.exe` in `Install-BinFile` where the target name is processed as `$name`

```
  $packageShimFileName = Join-Path $nugetExePath "$name.exe"
```

The shim construction needs to be updated to strip the `.exe` extension from the name before passing to `Install-BinFile`.

```
Get-ChildItem $installLocation -recurse -include '*.exe' | foreach-object {
  Install-BinFile -Name $_.Name -Path $_.FullName
}
```

**Comment by dgalbraith** [comment]
@AeliusSaionji this has now been corrected.

The update will take effect in the Chocolatey Community repository when the next build of Nushell (0.45+) is released.
