### ISSUE TITLE
Migrate maintenance of the diskmon package

### ISSUE THREAD

**Issue by dgalbraith** [dgalbraith/chocolatey-packages#397]
Migrate maintenance of the [duiskmon package](https://www.chocolatey.org/packages/diskmon) from the [dtgm repository](https://github.com/dtgm/chocolatey-packages).

**Comment by gep13** [comment]
This package was recently taken over by Thilas, so I don't think that any further work is required here.

**Comment by dgalbraith** [comment]
@gep13 noted - thanks.
