### ISSUE TITLE
(apache-directory-studio) Error 404 while downloading

### ISSUE THREAD

**Issue by weeix** [dgalbraith/chocolatey-packages#400]
### Command

```
choco install -y apache-directory-studio
```

### Result

```
apache-directory-studio v2.0.0.25 [Approved]
apache-directory-studio package files install completed. Performing other installation steps.
Attempt to get headers for http://apache.hippo.nl/directory/apacheds/dist/2.0.0.AM25/apacheds-2.0.0.AM25.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://apache.hippo.nl/directory/apacheds/dist/2.0.0.AM25/apacheds-2.0.0.AM25.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved: 'apache.hippo.nl'"
Downloading apacheds
  from 'http://apache.hippo.nl/directory/apacheds/dist/2.0.0.AM25/apacheds-2.0.0.AM25.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://apache.hippo.nl/directory/apacheds/dist/2.0.0.AM25/apacheds-2.0.0.AM25.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of apache-directory-studio was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\apache-directory-studio\tools\chocolateyInstall.ps1'.
 See log for details.
```

### Environment

- Chocolatey 1.1.0
- Windows 10 Home 21H1 (build 19043.1706) 64-bit

**Comment by dgalbraith** [comment]
@weeix I think that you are referencing a different product here - there are a number of similarly-named packages which are albeit installing different underlying packages.

The package in my repository is [apachedirectorystudio](https://community.chocolatey.org/packages/apachedirectorystudio/2.0.0-m17) which is a pre-release version (2.0.0-M17) and would be installed with the command `choco install apachedirectorystudio --pre`.  This package is for the Eclipse-based  LDAP browser and directory client being built under the Apache Directory project.  I believe that this package is correct and functioning as expected.

The package that you are referring to here is [apache-directory-studio](https://community.chocolatey.org/packages/apache-directory-studio) which is maintained by the Chocolatey user [dskowronski](https://community.chocolatey.org/profiles/dskowronski) and would be installed with the command `choco install apache-directory-studio`.  This package also comes under the Apache Directory Project but is for an LDAP and Kerberos server called ApacheDS.  As per your experience I see this package as broken and failing installation.

I am afraid that you will need to raise the issue with the Chocolatey user [dskowronski](https://community.chocolatey.org/profiles/dskowronski) to address using the [Contact Maintainers](https://community.chocolatey.org/packages/apache-directory-studio/ContactOwners) link on the package page.  If this doesn't elicit a response the next step would be to raise a new Package Maintainer Request on the [Chocolatey Community Package Requests repository](https://github.com/chocolatey-community/chocolatey-package-requests/issues).
