### ISSUE TITLE
Updat require on imageJ Chocolatey package

### ISSUE THREAD

**Issue by UNISTRAPHIOlivier** [dgalbraith/chocolatey-packages#403]
Hello, 

I just whant to ask you if it's possible to you to update the chocolatey package for imageJ:

https://community.chocolatey.org/profiles/dgalbraith

Many thanks in advance.

**Comment by dgalbraith** [comment]
@UNISTRAPHIOlivier thanks for flagging the issue.

This has now been addressed and the latest available version of ImageJ at the [NIH download page](https://imagej.nih.gov/ij/download.html) will be reflected in the Chocolatey package.
