### ISSUE TITLE
nushell is no longer automatically updating

### ISSUE THREAD

**Issue by binyomen** [dgalbraith/chocolatey-packages#404]
Hello!

It seems the [nushell package](https://community.chocolatey.org/packages/nushell) is no longer automatically updating. The current version in Chocolatey is 0.63.0, but the current release version is [0.65.0](https://github.com/nushell/nushell/releases/latest).

Thanks!

**Comment by dgalbraith** [comment]
@binyomen the format of the filenames produced by the build process has changed eg.  `nu_0_63_0_windows.msi` to `nu-0.65.0-x86_64-pc-windows-msvc.zip`.  The automated update script needs to be modified to account for this.
