### ISSUE TITLE
Nheko needs urgent update

### ISSUE THREAD

**Issue by opusforlife2** [dgalbraith/chocolatey-packages#432]
Hi, a bunch of Matrix apps were updated at the same time to fix a high severity vulnerability. Nheko is one of them: https://github.com/Nheko-Reborn/nheko/tree/v0.10.2

Is it possible to manually update the package instead of waiting for the bot?

**Comment by dgalbraith** [comment]
@opusforlife2 I have pushed an update for the v0.10.2 version and it is currently going though the automated review process.

As this is a trusted package it should be made available in the community repository immediately following this.

In the interim you could probably install/upgrade directly with a version specification `choco upgrade -y nheko-reborn --version 0.10.2` if required.

Note that the source code in GitHub will be out of sync until I push an update - I expect to do this later today.

**Comment by opusforlife2** [comment]
Off-topic: searching for Nheko in the repo at this very moment shows 0 results. Only after refreshing the page a bunch of times does it go back to showing the package with the previous version. I've only seen this happen when a package has a new version in the mod queue.

Have you experienced this? Is it a known bug?

**Comment by dgalbraith** [comment]
@opusforlife2 I do believe that this is a known problem relating to the setup of the caching infrastructure - see https://github.com/chocolatey/home/issues/8.

It is definitely a known issue and the Chocolatey staff are aware but not clear on any plans/timelines to address.
