### ISSUE TITLE
Beekeeper Studio install/portable packages outdated

### ISSUE THREAD

**Issue by IndrekHaav** [dgalbraith/chocolatey-packages#447]
The [beekeeper-studio](https://community.chocolatey.org/packages/beekeeper-studio) package has been updated to 3.7.9, but the [.install](https://community.chocolatey.org/packages/beekeeper-studio.install/) package it depends on is still at 3.6.2, so `choco upgrade` fails. Verification testing would have caught this, but the package is exempt.

The .portable package is likewise still at 3.6.2.

**Comment by mattcargile** [comment]
`choco install beekeeper-studio -y` is broken now too.

**Comment by dgalbraith** [comment]
Package updates are failing due to the structural changes on the GitHub asset pages as per packages fixed under gh-431.

Automatic update scripts need to cater to the revised asset page structure.

**Comment by IndrekHaav** [comment]
So is there a plan to fix the packages? Or are you waiting for someone to do a PR maybe? The meta package is now at 3.7.10.

Just wondering if there's any update...

**Comment by dgalbraith** [comment]
Package will be updated - breakage is down to an update on the GitHub hosting for artifacts associated with a build.

Pull requests welcome if they are incoming but will take a look - the additional GitHub changes that have impacted here are unclear at present.

**Comment by dgalbraith** [comment]
@IndrekHaav packages have now been resynced through the auto-updater and should track correctly going forward.
