### ISSUE TITLE
OpenVPN Package Version Update

### ISSUE THREAD

**Issue by dgalbraith** [dgalbraith/chocolatey-packages#452]
The OpenVPN package currently has no handling for minor versions.

Package should be updated to latest version 2.6.0-I004 with the addition of support for incremental minor versions in the package version + the automatic updater.

**Comment by lstipakov** [comment]
Hello @dgalbraith ,

We have [released](https://openvpn.net/community-downloads/) 2.6.0-I005, which:

- [fixes](https://github.com/OpenVPN/ovpn-dco-win/issues/36) occasional BSOD on machines with legacy standby (S3)
- [fixes](https://github.com/OpenVPN/ovpn-dco-win/issues/31) broken DCO adapter when Citrix DME Filter driver is installed
- [updates](https://github.com/OpenVPN/openvpn-build/commit/7a66032c6ee33bd1f31b3b5ab2f3411024071dcc) OpenSSL to 3.0.8

Please consider updating the port.

**Comment by dgalbraith** [comment]
Hello @lstipakov

Ready to push an update and handle these automatically going forward but would like to clarify the versioning scheme if possible.

Are you in a position to:

1. advise on the versioning scheme used eg. for say `2.6.0-I005` what are the components of the version identifier referring to given for a particular version there are multiple releases where only the `-I\d{3}` portion changes eg. `6.2.0-I004` was followed by `6.2.0-I005`.  Is this representing for example `Major`.`Minor`.`Patch`-I`Build`; and
2. confirm that the version section following on from the `-I` will always consist of 3 digits which are monotonically increasing?

**Comment by lstipakov** [comment]
Here is the meaning of version, for example `2.6.0-I005`:
 - `2.6.0` means the exact OpenVPN tag from which `openvpn.exe` and few other binaries (but not UI part, `openvpn-gui.exe`) were build
 - `I005` is incremented when some components, which are not part of openvpn repository, are updated, such as:
   - OpenSSL or other dependencies
   - ovpn-dco-win driver or other drivers
   - `openvpn-gui.exe` - the UI part of the client

When we build the client from the new tag, say, `2.6.1`, that `Ixxx` part got "reset", so the version will be `2.6.1-I001`. When we need to update only a component, say, OpenSSL or the driver, without updating openvpn, we bump `Ixxx`, so the next version will be `2.6.0-I006`.

Note that within MSI there is a product version, which is visible for example in `Add/Remove App` dialog (`2.6.010`):
![Näyttökuva 2023-02-24 153445](https://user-images.githubusercontent.com/643110/221191657-10b27d8e-51d6-48ae-88e2-4db756706165.png)

For `2.6` release this will grow like `2.6.011`, `2.6.012` and so on. Starting from `2.7` we'll have `2.7.001`.

**Comment by dgalbraith** [comment]
Hello @lstipakov

Many thanks for the comprehensive treatment on the versioning.

I have opted to use the tag version in conjunction with the increment for the Chocolatey package version.  With the scheme in place `OpenVPN 2.6.0-I005` would be mapped to version `2.6.0.005` for the corresponding Chocolatey package.

The package for `OpenVPN 2.6.0-I004` has been pushed to the Chocolatey community repository and is going through the moderation process.  There will be an additional update to `OpenVPN 2.6.5-I005` which will be pushed the next time the automated build pipeline is executed.
