### ISSUE TITLE
Choco Remote Desktop Client update loop

### ISSUE THREAD

**Issue by Jeremyp87** [dgalbraith/chocolatey-packages#482]
Hi,

Didn't know how to best reach you, hope this is ok. 

It appears choco is trying to upgrade this app every day resulting in it being exited. In the eventlog I can find below, it repeats every day while the version is not updated. This is on multiple computers, resulting in session disconnects. The installed version is the same as the version that's being installed/updated.

-Beginning a Windows Installer transaction: C:\Windows\TEMP\chocolatey\remote-desktop-client\1.2.4240\RemoteDesktop_1.2.4240.0_x64.msi. Client Process Id: 5984.
-Ending a Windows Installer transaction: C:\Windows\TEMP\chocolatey\remote-desktop-client\1.2.4240\RemoteDesktop_1.2.4240.0_x64.msi. Client Process Id: 5984.
-Windows Installer reconfigured the product. Product Name: Remote Desktop. Product Version: 1.2.4240.0. Product Language: 1033. Manufacturer: Microsoft Corporation. Reconfiguration success or error status: 0.
-Product: Remote Desktop -- Configuration completed successfully.

https://community.chocolatey.org/packages/remote-desktop-client

Thanks

**Comment by dgalbraith** [comment]
@Jeremyp87 that is not what I would expect based on Chocolatey standard behavior.

Normally Chocolatey will only update packages with a ```choco upgrade remote-desktop-client``` or picking up the ```remote-desktop-client``` package as part of a ```choco upgrade all```.

Was the package perhaps set to allow the RDS client to update automatically - this is what it I _think_ might be happening here.

**Comment by dgalbraith** [comment]
This can be checked on the Remote Desktop client - if you navigate through the more options elipsis / ... --> about menu

<img width="283" alt="image" src="https://github.com/dgalbraith/chocolatey-packages/assets/1270002/f222d220-4c91-4995-895d-138049dfaf48">

you will see an indication on whether automatic updates are enabled.

**Comment by Jeremyp87** [comment]
We do run choco upgrade all on the computers once a day, but that should only upgrade packages that are out of date. MSRDP is updated as well during this process, while it is on the current level.

We stepped away from this choco package and are now updating manually with PowerShell.

**Comment by dgalbraith** [comment]
@Jeremyp87 I don't see that behavior at the package level - what I see is the package operating as expected.

The version detection is actually at the Chocolatey level so the upgrade being initiated there.  Once it does so the client shutdown is actually initiated by the Windows installer - there is nothing in the package install script to kill an existing process or session.

While I know you have a work-around is the daily upgrade being forced ```-f, --force```?

Both a bulk upgrade and a direct upgrade of the package don't exhibit the behavior that you were seeing.

<img width="733" alt="image" src="https://github.com/dgalbraith/chocolatey-packages/assets/1270002/5b3a854a-3170-4d65-a90d-a5e270951495">

<img width="764" alt="image" src="https://github.com/dgalbraith/chocolatey-packages/assets/1270002/bff64054-87cd-449e-80b8-be6d3f9a3646">

**Comment by Jeremyp87** [comment]
@dgalbraith , at this time I can't reproduce it anymore. At the time of opening this issue, it was 100% reproducible and it occurred on all our computers.

**Comment by dgalbraith** [comment]
Closing as non-reproducible for now.  Will revisit if there are further occurrences.
