### ISSUE TITLE
The automatic update of package bluej is failing.

### ISSUE THREAD

**Issue by fame-zhaw** [dgalbraith/chocolatey-packages#488]
The package [BlueJ](https://community.chocolatey.org/packages/bluej) is not being updated. 

The current version is Version 5.2.0, released 20 June 2023 (see [BlueJ Webpage](https://www.bluej.org/))

**Comment by dgalbraith** [comment]
The package was updated automatically but it failed a moderation check and was ultimately rejected.

Will update to address this and ask the admins to re-open the package version so it can be addressed and pushed.

**Comment by dgalbraith** [comment]
Actually it looks like a bug with the validator.  The issue flagged relates to the ```ProjectSourceUrl```

![image](https://github.com/dgalbraith/chocolatey-packages/assets/1270002/95f4d052-be0a-4ed6-88e6-1c8af4283a89)

but there is no issue - the ```ProjectSourceUrl``` is correct.

It does look like the source code is now hosted on GitHub though so the URL can be updated to reflect this.

**Comment by dgalbraith** [comment]
@fame-zhaw this should now be addressed and a non-issue going forward.  The package is undergoing moderation but if you need to udpate prior you can install with the version ```5.2.1``` - ```choco install bluej --version=5.2.1```.
