### ISSUE TITLE
OpenVPN /PLAP Option broken after Merge like bevor | Merged ps1 not Live

### ISSUE THREAD

**Issue by Lun4r161** [dgalbraith/chocolatey-packages#524]
Installstring for Chocy:
openvpn --package-parameters="/AddToDesktop /GUI /DcoDriver /TapDriver /WintunDriver /OpenSSL /Service /GuiOnLogon /PLAP"

Code in the MSI log after crashed Installation:
OpenVPN-2.6.8-I001-amd64.msi" /qn /norestart ADDLOCAL="
Drivers.TAPWindows6,
Drivers.Wintun,
OpenVPN.GUI,
OpenSSL,
OpenVPN.GUI.OnLogon,
OpenVPN.Service,
OpenVPN.PLAP, <---- Wrong, correct is OpenVPN.PLAP.Register
Drivers.OvpnDco"

**The chocolateyInstall.ps1 on github looks fine after the merge but is not LIVE:**
 'PLAP' {
	      Write-Verbose('Pre-Logon Access-Provider will be activated')
	      $local += 'OpenVPN.PLAP.Register'
      }

After a crashed Installation i find under "lib-bad" (i cleared it before) in the Chocy Folder the chocolateyInstall.ps1 with date of 28.11.2023 and the wrong code:

 'PLAP' {
	      Write-Verbose('Pre-Logon Access-Provider will be activated')
	      $local += 'OpenVPN.PLAP'
      }

**Comment by dgalbraith** [comment]
Updated version of the package containing the corrected PLAP handling available in the community repository - any verision after ``` 2.6.9.001``` will have this fix.
