### ISSUE TITLE
SSRS-2019 package update failing

### ISSUE THREAD

**Issue by dgalbraith** [dgalbraith/chocolatey-packages#564]
The automatic update for the [ssrs-2019 package](https://community.chocolatey.org/packages/ssrs-2019) is failing.

![image](https://github.com/dgalbraith/chocolatey-packages/assets/1270002/556cfae4-9f5c-4fad-853a-b5e70ce21553)

**Comment by eppNator** [comment]
Hello dgalbraith, my DBA pointed out that there is a newer release of SSRS 2019 and the nuspec file says to contact you if the chocolatey package isn't automatically updated so I'm hoping that you get this message and are able to manually update the package. Thanks for your work on this!!

**Comment by dgalbraith** [comment]
@eppNator a manual package update has been pushed as an interim solution
